language: elixir
cache:
  directories:
    - deps
    - _build
services:
  - docker
  - postgresql
addons:
  postgresql: "9.5"
  apt:
    packages:
      - wkhtmltopdf
      - docker-ce
elixir:
  - 1.5.2
otp_release:
  - 20.1
notifications:
  slack:
    rooms:
      - secure: "X1blJFdb5wpHSOinf25Do2JeOSHJZKH4mi+tjgdllABOFVi0bQpsiUa2DeMNeZ11mYuiwur48IPkpVJI/CjgLiZxGldrRwp+7zav0WXB6kLcWgK2dR1I1f9qhWOAojAnbnzcQ/kKCYJ2GGnA+mO/Pf6yi+qYaJVjkMZTr0QxKFXHx8+4X7lLJkw9r1C2Q0KlgwQ08hrLjXG3a77+dnc214aMN3Y8z9pDaqwx5szHEkHV/uJVWJSPiQD3xQRhEpadS5SykOAxlIzggPvDpplW+xcUmvVl5RtEw9RXJ+0/nwNwauexzk9Xj3RKYv0tt5QFubQRY7WhbijTabtS8Gp6Mvle4CohV2IbAhK7byRJ+iJ4Abmi4taz/iPBIlRESvK1NeX1Dn+EpznWRd1LvUnK/G6j2M0W2/tnn3XCl0IcWbtsL4oEeH4aXIDI8o3FQ1nhbe0WzfuLcC5JrSzp80zbWvidOR3J7LzKBGj+id2eMNN+uEf/eOiuP0FylJbxLBsLA5fIIbdkkDmRd9VtgfAI05FeHSCbHCnpBfuOGrRHU61DroYsGUkvFI+ZTuCVT6nKpSKfwyxYkaPpr3FUy4hNFvS2C3Noj4JVrkfbAGIw336e84PO4lfnwwjW9AefpgD6SMNu7q0x3dyRMjTWJpSQbdJQOZJMRmuU3q9uwIBafCw="
    on_success: always
env:
  global:
    - Chart=man
    - MIX_ENV=test
    - MAIN_BRANCHES="master develop preprod" # Branches on which you want version to be incremented
    - RELEASE_BRANCH="develop"
    # Docker
    - DOCKER_HUB_ACCOUNT=edenlabllc
    - secure: "sK/G0Xf1vkNa+tYFU/zKqvuqupfd9xFRJoULXbC1THlOkP57W+Btt6pVRtKmn1L7ZTCf+QPHO/uNLuwzu5e7w5A4oQjiNDLQwVhsAa0C2w8LPW4ujJiBYec+Y0nGwZgreVVUAG5OAj3Cm2caibumN6u3Zxngu9vJ3uF/QyoFD9XYqVq48+o/ydabNieTgvHIhaw1vE0wF3kUzzqDAW2VgCtE1lFEd0wtuliUH9R0wztQSOqPIBD98ckJTxwFssFCLxQgpDYJvdHGi9uZxWeD5YLO7DAmZJDf6xs2QL90xUKivYBJ5qytbEoycTSVkgeYwF5bh0pdBno5u0qk5qPFeOi4jx+e8miugoLc2SMsTrH1G/dkkxbktNLB5cQhEPPxT6MWWFWuv9BZfp80slPDQ6W/e8+Q9Zzf9k8Si5nIPDRzBXSZ9FqUlJg7FtXBA9MCxUXHT4Hxjz6DDeO/fEHrRKuH1Ms6UVQBoQiMxsDpAvaTrcrQwV9AvJdVp1Txom3kotZ1UjJUTm9xQ8JVAlxEJ1pXYFVutMlKVOBcWLihl5SnbjdYW17Ilgu0QIVOuuy9mRtp1PXDC8uso5ZTegn3DhS/5UHP8DD+LcMkNLi74frozaAIGUFm0Lygx8vH/bkYG0+rqip5HoiHUldGOIN8G0mXJLMPNjLcArpr2tr46BE="
    # GitHub
    - secure: "W5+0Z3d45edOTpfqumZ+BjIO5RxCvNL+kP8MBZxOmPS2gUmCGyw7zj9RzaMMq2ipoUeInfD+yn2P4nND0qJt1Tv65+8Gs4wj1Y+onagurWUHLdvoeIMx5xgkTkHfxAH6bnmylCCRtmsneXqB+uyAuN4s96iVsdNGps3Y7ZXUI77lFcTL4DoojXB2oiuKkhvHckWD5AaJD2lRjx3Cc48snttwJbQoHj5yoe7PU8fqbIUAXd19O7crNlFnN/ujDcor276rHj8n6duin7xGE9DCmWGZC7aYyfWw9YMUM4axC6zqli3uj4Jzks0zZMkDN8M2Zcw497FiwdYSra7PcQOJV+skPbX4n2o8LcfG1jhyTchtpVEQueIgh/36E+F3DfPCzQI1d2ubJZCwSVcTqa3zD+ZKe0watkKJBeezAMhhJH19wUMBP6dYKmm9y5LcPX/FvIoqrVo7o+fxky4e4xzg9UisXqSg9s7/9iGBJSKnFG+rJIII0yIOV6JH0T86qYOvyq0oN2sJrfqcD2KKK9HmGtAuGnMpVWU8OcmT3QO/Ehc+P6ynV9v+01nT6Mp2lzX5+pRfhtvdfC6clBqdLsaneCIzWwhlcIlJ3cI9WJMULuv+3+0ovvqJItdIMFzMFTrPxGL4Q0EbdDVAlOu3pujU0fnnS1GII3+1Sj+ulHwDlqg="
branches:
  # Releases are generated automatically, stop infinite build loop
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  # Expose MQ and DB to Docker container
  - sudo ./bin/ci/init-db.sh
before_script:
  # Run X server to for wkhtmltopdf
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  # Increment version in mix.exs
  - ./bin/ci/version-increment.sh || travis_terminate 1
  # Install dependencies
  - mix deps.get || travis_terminate 1
  # Run all tests except pending ones
  - ./bin/mix_tests.sh || travis_terminate 1
  # Build Docker container
  - ./bin/build.sh || travis_terminate 1
  # Initialize DB for Docker container
  - MIX_ENV=dev mix ecto.setup
  # Run Docker container
  - sudo ./bin/start.sh || travis_terminate 1
  # Run acceptance tests on Docker container
  - "CONTAINER_HTTP_HOST=localhost CONTAINER_HTTP_PORT=4000 mix test test/acceptance"
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/push.sh || travis_terminate 1
  # CD to Dev
  - openssl aes-256-cbc -K $encrypted_7f8388603e86_key -iv $encrypted_7f8388603e86_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
  - sudo ./bin/deploy.sh || travis_terminate 1
