FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Mán Templates Rendering Service

Mán - templates rendeing as a service.

> "Mán" translates from the Sindarin as "Spirit". Sindarin is one of the many languages spoken by the immortal Elves.

## Introduction

Man consists of two main parts:

- Back-end that stores and renders Templates and provider REST API for them.
- UI that works on top of REST API and simplifies Templates management.

## Use Cases

- Rendering Email or SMS templates before sending them;
- API to render HTML pages.

## UI

> Screenshots

## Perfomance

## Setup Guide

### Docker

- API Docker container;
- UI Docker container.

### Heroku

[Install]().

## Templates [/templates]

### Search for a Template [GET /templates{?limit,starting_after,ending_before,labels}]

+ Parameters
    + labels: `label-name1,label-name2` (string, optional) - Label names to filter Templates list.
    + limit: 20 (number, optional) - A limit on the number of objects to be returned, between 1 and 100. Default: 50.
    + starting_after: 56c31536a60ad644060041af (string, optional) - A cursor to fetch next page. Taken from collection response.
    + ending_before: 56c31536a60ad644060041aa (string, optional) - A cursor to fetch previous page. Taken from collection response.

+ Response 200 (application/json)
    + Attributes (Response_Collection)
        + data (array[Template])

### Create Template [POST]

+ Request (application/json)
    + Attributes (Template)

+ Response 201 (application/json)
    + Attributes (Response_OK)
        + meta (Response__Meta)
            + code: 201 (number)
        + data (Template)

### Get Template by ID [GET /templates/{id}]

+ Parameters
    + id: 58e2278a84092e61700041a7 (string, optional) - Template ID

+ Response 200 (application/json)
    + Attributes (Response_OK)
        + data (Template)

### Replace Template [PUT /templates/{id}]

+ Parameters
    + id: 58e2278a84092e61700041a7 (string, optional) - Template ID

+ Request (application/json)
    + Attributes (Template)

+ Response 200 (application/json)
    + Attributes (Response_OK)
        + data (Template)

### Update Template [PATCH /templates/{id}]

+ Parameters
    + id: 58e2278a84092e61700041a7 (string, optional) - Template ID

+ Request (application/json)
    + Attributes (Template)
        + body: `<h1>{{user_name}}</h1>` (string, optional)

+ Response 200 (application/json)
    + Attributes (Response_OK)
        + data (Template)

### Delete Template [DELETE /templates/{id}]

+ Parameters
    + id: 58e2278a84092e61700041a7 (string, optional) - Template ID

+ Request (application/json)
+ Response 200 (application/json)

### Render Template [POST /templates/{id}/actions/render]

Rendering request is validated by JSON Schema that is set in Template.

+ Parameters
    + id: 58e2278a84092e61700041a7 (string, optional) - Template ID

+ Request (application/json)
    + Headers

            Accept-Language: en-US

    + Attributes (object)
        + locale: en_US (string, optional) - Locale of template that should be rendered. Required when `Accept-Language` header is not set.
        + data (object, required)
            + user_name: Alex (string) - Template data that should be used by rendering engine.

+ Response 200 (text/plain)
    + Body

            <h1>Alex</h1>

+ Response 404 (application/json)
    + Attributes (`Response_Error`)
        + meta
            + code: 404
        + error
            + type (enum, required)
                - `locale_not_found`
                - `template_not_found`

+ Response 422 (application/json)
    + Attributes (`Response__Error_ValidationFailed`)

## Labels Collection [/labels]

### Get all defined labels [GET]

+ Request (application/json)
+ Response 200 (application/json)
    + Attributes (Response_OK)
        + data (array[string])
            + `group/emails` (string, required)
            + `action/signup` (string, required)

# Data Structures
## Responses
### `Response_Collection`
+ meta (Response__Meta, fixed-type)
+ data (array[], fixed-type)
+ paging (Response__Pagination, fixed-type)

### `Response_OK`
+ meta (Response__Meta, fixed-type)
+ data (object, fixed-type)

### `Response__Process_OK`
+ meta (Response__Meta, fixed-type)
+ data (object, fixed-type)
    <!-- + affordances (array[Affordance], required) - List of available affordances and their URLs -->

### `Response_Error`
+ meta (Response__Meta, fixed-type)
    + code: 400 (number)
+ error (Response__Error, fixed-type)

### `Response__Meta`
+ code: 200 (number) - HTTP response code.
+ url: http://example.com/resource (string) - URL to requested resource.
+ type (enum) - Type of data that is located in `data` attribute.
    - object (string) - `data` attribute is a JSON object.
    - list (string) - `data` attribute is a list.
+ code: 200 (number) - HTTP response code.
+ `idempotency_key`: `idemp-ssjssdjoa8308u0us0` (string, optional) - [Idempotency key](http://docs.apimanifest.apiary.io/#introduction/optional-features/idempotent-requests). Send it trough `X-Idempotency-Key` header.
+ `request_id`: `req-adasdoijasdojsda` (string) - [Request ID](http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/request-id). Send it with `X-Request-ID` header.

### `Response__Error`
+ type: type_atom (string) - Atom that represents error type.
+ message: Error description (string) - Human-readable error message. This is for developers, not end-users.

### `Response__Error_DuplicateEntity`
+ type: `object_already_exists` (string) - Atom that represents error type.
+ message: This API already exists (string) - Human-readable error message. This is for developers, not end-users.

### `Response__Error_ValidationFailed`
+ type: validation_failed (string) - type of an error.
+ message: Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors. (string)
+ invalid (array)
    + `entry_type`: `json_data_proprty` (string) - Type of error.
    + entry: $.cvv (string) - JSON Path to an invalid property.
    + rules (array)
        + rule: required (string) - String constant that represents validation rule type. List of all types can be found in [API Manifest](http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors).
        + params (array) - Validation Parameters.

### `Response__Pagination`
+ limit: 20 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50.
+ cursors (object)
    + `starting_after`: 56c31536a60ad644060041af (string) - A cursor for use in pagination. An object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.
    + `ending_before`: 56c31536a60ad644060041aa (string) - A cursor for use in pagination. An object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.
+ size: 1000 (number) - Total number of objects in collection.
+ has_more: false (boolean) - Is this collection have more data to load in the same style as last request loaded it.

## Templates
### Template 
+ id: 58e2278a84092e61700041a7 (string, optional)
+ title: `Sign-Up Email` (string, required)
+ description: `Email that is sent on signup process` (string, optional)
+ syntax: mustache (enum, optional) - Syntax processor for a template
    + mustache
    + markdown
+ sources (array[Template__Source], required)
+ labels (array[string], optional)
    + `group/emails` (string)
    + `action/signup` (string)
    + `other_tag` (string)
+ validation_schema: `{}` (string, optional) - JSON Schema to validate requests to the template.

### `Template__Source`
+ locale: en_US (string, required) - Locale for defined template
+ body: `<h1>{{user_name}}</h1>` (string, required) - Template that should be rendered with `syntax` processor.