use Mix.Config

# Configuration for production environment.
# It should read environment variables to follow 12 factor apps convention.

# Configure your database
config :man_api, Man.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: {:system, "DB_NAME"},
  username: {:system, "DB_USER"},
  password: {:system, "DB_PASSWORD"},
  hostname: {:system, "DB_HOST"},
  port: {:system, :integer, "DB_PORT"}

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# Man.Web.Endpoint.load_from_system_env/1 dynamically.
# Any dynamic configuration should be moved to such function.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :man_api, Man.Web.Endpoint,
  on_init: {Man.Web.Endpoint, :load_from_system_env, []},
  http: [
    port: {:system, "PORT", "80"},
    protocol_options: [max_keepalive: 1_000_000]
  ],
  url: [
    host: {:system, "HOST", "localhost"},
    port: {:system, "PORT", "80"}
  ],
  secret_key_base: {:system, "SECRET_KEY"},
  debug_errors: false,
  code_reloader: false

# Do not log passwords, card data and tokens
config :phoenix, :filter_parameters, ["password", "secret", "token", "password_confirmation", "card", "pan", "cvv"]

config :phoenix, :serve_endpoints, true

config :pdf_generator, wkhtml_path: "/bin/wkhtmltopdf"

config :logger, level: :info, handle_otp_reports: true
